version: '3.4'
services:
  web:
    image: "xwiki:stable-mysql-tomcat"
    depends_on:
      - db
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DB_USER=xwiki
      - DB_PASSWORD=xwiki
      - DB_HOST=db
    volumes:
      - web-volume:/usr/local/xwiki
    networks:
      - network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.capabilities.web == yes]
  db:
    image: "mysql:latest"
    restart: always
    volumes:
      # - ./xwiki.cnf:/etc/mysql/conf.d/xwiki.cnf
      - db-volume:/var/lib/mysql
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=xwiki
      - MYSQL_USER=xwiki
      - MYSQL_PASSWORD=xwiki
      - MYSQL_DATABASE=xwiki
    networks:
      - network
    deploy:
      placement:
        constraints: [node.labels.capabilities.storage == yes]
    configs:
      - source: init_sql
        target: /etc/mysql/conf.d/xwiki.cnf
      - source: xwiki_cfg
        target: /docker-entrypoint-initdb.d/init.sql
volumes:
  db-volume:
    name: apice-db-volume
  web-volume: 
    name: apice-xwiki-volume
networks:
  network:
    driver: overlay
    attachable: true
configs:
  init_sql:
    file: ./init.sql
  xwiki_cfg:
    file: ./xwiki.cfg
